seed: 1234
lr: 1e-04
clip-norm: 0.1
dropout: 0.2
max-tokens: 4000
warmup: 1000
num_workers: 4
limit_val_batches: 0.005
limit_test_batches: 0.005
limit_train_batches: 0.002
max_input_len: 2048
max_output_len: 128
val_every: 0.33
batch_size: 2
eval_batch_size: 2
grad_accum: 1
fp16: False
grad_ckpt: True
attention_window: 256
num_epochs: 10
use_entity_embeddings: False
model_name: allenai/led-base-16384
trained_model_path: 
data_dir: /data
output_dir: ./saved_models/test
clearml_dataset_project_name: datasets/squad1.1
clearml_dataset_name: nqg
clearml_dataset_tags: []
debug: False
train: True
test: True
role_list: ["PerpInd", "PerpOrg", "Target", "Victim", "Weapon"]

